// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Mon, 09 Dec 2013 18:14:11 GMT
 
using System.Reflection;
 
[assembly: AssemblyVersion("2.0.16709.0")]
[assembly: AssemblyFileVersion("2.0.16709.1814")]