// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Tue, 10 Dec 2013 06:24:08 GMT
 
using System.Reflection;
 
[assembly: AssemblyVersion("2.0.16710.0")]
[assembly: AssemblyFileVersion("2.0.16710.624")]