// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Sun, 28 Jul 2024 14:19:55 GMT

using System.Reflection;

[assembly: AssemblyVersion("3.4.29428.0")]
[assembly: AssemblyFileVersion("3.4.29428.1419")]
