// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Wed, 21 Dec 2016 08:43:43 GMT

using System.Reflection;

[assembly: AssemblyVersion("3.3.20321.0")]
[assembly: AssemblyFileVersion("3.3.20321.843")]
