// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Fri, 02 Aug 2024 16:33:52 GMT

using System.Reflection;

[assembly: AssemblyVersion("3.3.29502.0")]
[assembly: AssemblyFileVersion("3.3.29502.1633")]
