// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Tue, 08 Dec 2015 21:41:50 GMT

using System.Reflection;

[assembly: AssemblyVersion("2.0.19108.0")]
[assembly: AssemblyFileVersion("2.0.19108.2141")]