// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Tue, 18 Aug 2015 17:03:26 GMT

using System.Reflection;

[assembly: AssemblyVersion("2.0.18718.0")]
[assembly: AssemblyFileVersion("2.0.18718.1703")]