// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Thu, 20 Oct 2016 06:08:37 GMT

using System.Reflection;

[assembly: AssemblyVersion("3.1.20120.0")]
[assembly: AssemblyFileVersion("3.1.20120.608")]