// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Fri, 11 Dec 2015 07:45:17 GMT
 
using System.Reflection;
 
[assembly: AssemblyVersion("3.1.19111.0")]
[assembly: AssemblyFileVersion("3.1.19111.745")]